### ISSUE TITLE
Add Velocity Support

### ISSUE THREAD

**Issue by Ghosflot** [Lably-Team/ChatLab#39]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example. I'm always frustrated when [...]

**Describe the solution you'd like**

**Additional Information**

**Comment by Ghosflot** [comment]
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example. I'm always frustrated when [...]

Describe the solution you'd like
A clear and concise description of what you want to happen.

Additional Information
Add any other context or screenshots about the feature request here.

**Comment by BryanGamingDV** [comment]
@4drian3d

**Comment by Ghosflot** [comment]
can you kis mi bryan

**Comment by 4drian3d** [comment]
What do you mean by supporting Velocity? What features would you like to see there? 
Please fill out the template correctly
