### ISSUE TITLE
Errors in console (Paper 1.18.1)

### ISSUE THREAD

**Issue by leolnid** [Lably-Team/ChatLab#43]
**Describe the bug**
Error in console

**Console Error**
https://paste.gg/p/anonymous/d4d2e0fd12874187a5a7ecdc3a09204a

**Server Version**
This server is running Paper version git-Paper-148 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cb198ff)
You are running the latest version
Previous version: git-Paper-147 (MC: 1.18.1)

**Comment by BryanGamingDV** [comment]
Thx, will be fixed in the next version
